'use strict';
const URL_SB='https://chkczeusxnifayswhvqo.supabase.co',KEY='sb_publishable_ylT-mRYXiTu-KHp-aD8J9w_EVv9Xz6p',ENDPOINT=URL_SB+'/functions/v1/school-image-upload';
const db=supabase.createClient(URL_SB,KEY),$=id=>document.getElementById(id);let user=null,records=[],selected=null,pending=null,busy=false,previewURL=null,cloudReady=false;
const STATUS_JWT='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoa2N6ZXVzeG5pZmF5c3dodnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA2OTM4NDUsImV4cCI6MjEwNjI2OTg0NX0.KA_1VvZRDnFLJP36ukVkWLNR4UQkZnv6T-CJ-73eijA';
const say=t=>{$('message').textContent=t;};
const size=n=>(n/1024).toLocaleString('ar-BH',{maximumFractionDigits:0})+' كيلوبايت';
const date=t=>new Date(t).toLocaleString('ar-BH',{timeZone:'Asia/Bahrain'});
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
async function storage(action,value){const d=await new Promise((resolve,reject)=>{const r=indexedDB.open('school-image-test',1);r.onupgradeneeded=()=>r.result.createObjectStore('pending');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const tx=d.transaction('pending',action==='get'?'readonly':'readwrite'),s=tx.objectStore('pending');const req=action==='get'?s.get(user.id):action==='put'?s.put(value,user.id):s.delete(user.id);let result;req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}finally{d.close();}}
async function compress(file) {
  if (!/^image\/(jpeg|png|webp|bmp)$/.test(file.type)) throw Error('اختر صورة JPG أو PNG أو WebP أو BMP.');
  if (file.size > 20 * 1024 * 1024) throw Error('حجم الصورة أكبر من 20 ميجابايت.');
  const compressed = await imageCompression(file, {
    maxSizeMB: 500 / 1024,
    maxWidthOrHeight: 1024,
    initialQuality: 0.85,
    maxIteration: 20,
    useWebWorker: true,
    fileType: 'image/jpeg',
    preserveExif: false,
    libURL: 'https://cdn.jsdelivr.net/npm/browser-image-compression@2.0.2/dist/browser-image-compression.js'
  });
  let uploadFile = compressed;
  if (file.type === 'image/jpeg' && file.size < compressed.size) {
    const src = URL.createObjectURL(file);
    try {
      const img = new Image();
      img.src = src;
      await img.decode();
      if (Math.max(img.naturalWidth, img.naturalHeight) <= 1024) uploadFile = file;
    } finally { URL.revokeObjectURL(src); }
  }
  if (!uploadFile || uploadFile.size > 500 * 1024) throw Error('تعذر تقليل الصورة إلى 500 كيلوبايت. اختر صورة أصغر.');
  return { blob: uploadFile, original: file.size };
}
async function pick(file){if(!file)return;if(busy)return;try{say('جاري تجهيز الصورة…');selected=await compress(file);if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(selected.blob);const img=new Image();img.src=previewURL;img.alt='معاينة الصورة المختارة';$('preview').replaceChildren(img);const delta=Math.round((1-selected.blob.size/selected.original)*100);$('sizes').textContent='الأصل: '+size(selected.original)+' • جاهزة للرفع: '+size(selected.blob.size)+(delta>0?' • تقليل '+delta+'٪':'');say('الصورة جاهزة.');}catch(e){say(e.message);}}
function render(){ $('count').textContent=records.length;const area=$('records');area.replaceChildren();for(const r of records){const c=document.createElement('article');c.className='record';const img=new Image();img.src=r.image_url;img.alt=r.name;img.loading='lazy';const section=document.createElement('section'),title=document.createElement('h3'),d=document.createElement('p'),a=document.createElement('a'),btn=document.createElement('button');title.textContent=r.name;d.className='muted';d.textContent=date(r.created_at);a.href=r.image_url;a.target='_blank';a.rel='noopener';a.textContent='فتح الصورة ↗';btn.textContent='نسخ الرابط';btn.onclick=async()=>{try{await navigator.clipboard.writeText(r.image_url);say('تم نسخ رابط الصورة.');}catch{say('افتح الصورة وانسخ الرابط من المتصفح.');}};section.append(title,d,a,document.createElement('br'),btn);c.append(img,section);area.append(c);}if(!records.length){const p=document.createElement('p');p.className='muted';p.textContent=user?'لا توجد سجلات محفوظة بعد.':'سجّل الدخول لعرض سجلاتك.';area.append(p);}}
async function load(){if(!user){records=[];render();return;}const{data,error}=await db.from('school_image_records').select('*').order('created_at',{ascending:false});if(error){say('تعذر جلب السجلات: '+error.message);return;}records=data||[];render();}
async function status(){try{const r=await fetch(ENDPOINT,{headers:{apikey:KEY,Authorization:"Bearer "+STATUS_JWT}});if(!r.ok)throw Error();const s=await r.json();cloudReady=s.ready;$('cloudStatus').classList.toggle('ready',cloudReady);$('cloudStatus').textContent=cloudReady?'جاهز: تُحفظ الصور في Cloudinary والسجلات في Supabase.':'الواجهة جاهزة. تفعيل رفع Cloudinary ينتظر إضافة المفتاح السري في إعدادات الخادم. يمكنك تجربة اختيار الصورة ومعاينة PDF الآن.';}catch{$('cloudStatus').textContent='تعذر التحقق من خدمة الرفع. أعد المحاولة عند عودة الاتصال.';}}
async function session(){const{data}=await db.auth.getSession();user=data.session?.user||null;$('authButton').textContent=user?'تسجيل الخروج':'تسجيل الدخول';$('account').textContent=user?'مسجل باسم '+user.email+' • توقيت البحرين':'سجّل الدخول بحساب تطبيق الفعاليات لعرض السجلات وحفظها.';pending=null;if(user){try{pending=await storage('get')||null;}catch{say('تعذر الوصول إلى الحفظ المؤقت على الجهاز.');}}renderPending();await load();}
function renderPending(){$('pending').hidden=!pending;$('pendingText').textContent=pending?'يوجد سجل «'+pending.name+'» محفوظ مؤقتًا على هذا الجهاز، ولم يتأكد حفظه في قاعدة البيانات.':'';}
function controls(value){busy=value;for(const id of['saveButton','retryButton','galleryButton','cameraButton','clearButton','name','authButton'])$(id).disabled=value;}
async function send(item){controls(true);try{const{data}=await db.auth.getSession();if(!data.session)throw Error('سجّل الدخول أولًا.');const form=new FormData();form.set('file',item.blob,'photo.jpg');form.set('name',item.name);form.set('id',item.id);form.set('original_bytes',String(item.original));say('جاري رفع الصورة وحفظ السجل…');const r=await fetch(ENDPOINT,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+data.session.access_token},body:form});const out=await r.json();if(!r.ok)throw Error(out.error||'تعذر الحفظ.');if(!out.record?.id)throw Error('لم يصل تأكيد الحفظ.');await storage('delete');pending=null;renderPending();clear();say('تم رفع الصورة إلى Cloudinary وحفظ السجل في Supabase.');await load();}catch(e){say(e.message+'\nالسجل محفوظ مؤقتًا؛ يمكنك إعادة المحاولة. لا تمسح بيانات المتصفح قبل حفظه.');}finally{controls(false);}}
function clear(){selected=null;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;$('name').value='';$('gallery').value='';$('camera').value='';$('preview').replaceChildren();const span=document.createElement('span');span.className='muted';span.textContent='ستظهر الصورة هنا';$('preview').append(span);$('sizes').textContent='حد الصورة الأصلية: 20 ميجابايت';say('');}
async function makePDF(list){if(!list.length)throw Error('لا توجد بيانات للتصدير.');await document.fonts.ready;const pdf=new jspdf.jsPDF('p','mm','a4'),stage=$('reportStage');try{for(let i=0;i<list.length;i++){const r=list[i],sheet=document.createElement('section');sheet.className='report-sheet';const school=document.createElement('p'),title=document.createElement('h1'),name=document.createElement('div'),time=document.createElement('p'),img=new Image(),credit=document.createElement('small');school.textContent='مدرسة النعيم الثانوية للبنين';title.textContent='تقرير الاسم والصورة';name.className='report-name';name.textContent=r.name;time.textContent=date(r.created_at)+(r.preview?' • معاينة محلية قبل الرفع':'');img.crossOrigin='anonymous';img.src=r.image_url;img.alt=r.name;await img.decode();credit.textContent='إعداد المدير المساعد: زياد الهاشمي • '+(i+1)+' / '+list.length;sheet.append(school,title,name,time,img,credit);stage.replaceChildren(sheet);const canvas=await html2canvas(sheet,{scale:1.5,backgroundColor:'#ffffff',useCORS:true});if(i)pdf.addPage();const w=194,h=canvas.height*w/canvas.width;pdf.addImage(canvas.toDataURL('image/jpeg',.92),'JPEG',8,8,w,Math.min(h,281));}pdf.save('تقرير_الاسم_والصورة.pdf');}finally{stage.replaceChildren();}}
async function excel(){if(!records.length)throw Error('لا توجد سجلات محفوظة للتصدير.');const wb=new ExcelJS.Workbook();wb.creator='زياد الهاشمي';const ws=wb.addWorksheet('الاسم والصورة',{views:[{rightToLeft:true,state:'frozen',ySplit:4}]});ws.columns=[{width:7},{width:32},{width:29},{width:65},{width:22},{width:22}];ws.mergeCells('A1:F1');ws.getCell('A1').value='مدرسة النعيم الثانوية للبنين — تقرير الاسم والصورة';ws.getCell('A1').font={name:'Arial',size:18,bold:true,color:{argb:'FF123E49'}};ws.getRow(1).height=42;ws.mergeCells('A2:F2');ws.getCell('A2').value='إعداد المدير المساعد: زياد الهاشمي | '+date(new Date());ws.getRow(4).values=['#','الاسم','وقت التسجيل — البحرين','رابط الصورة','الحجم الأصلي KB','الحجم المخزن KB'];records.forEach((r,i)=>ws.addRow([i+1,r.name,date(r.created_at),{text:'عرض الصورة',hyperlink:r.image_url},Math.round(r.original_bytes/1024),Math.round(r.stored_bytes/1024)]));ws.autoFilter='A4:F'+(records.length+4);ws.eachRow((row,n)=>{if(n<4)return;row.height=34;row.eachCell(c=>{c.font={name:'Arial',size:14,color:{argb:n===4?'FFFFFFFF':'FF173A43'},bold:n===4};c.alignment={vertical:'middle',horizontal:'right',wrapText:true};c.border={bottom:{style:'thin',color:{argb:'FFDCE6E3'}}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:n===4?'FF123E49':n%2?'FFF0F6F3':'FFFFFFFF'}};});if(n>4)row.getCell(4).font={name:'Arial',size:14,color:{argb:'FF056B56'},underline:true};});const b=await wb.xlsx.writeBuffer();download(new Blob([b],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'الاسم_ورابط_الصورة.xlsx');}
async function exportRun(fn){const ids=['excelButton','pdfButton','previewPDF'];ids.forEach(id=>$(id).disabled=true);try{say('جاري تجهيز الملف…');await fn();say('تم تنزيل الملف.');}catch(e){say('تعذر التصدير: '+e.message);}finally{ids.forEach(id=>$(id).disabled=false);}}
$('galleryButton').onclick=()=>$('gallery').click();$('cameraButton').onclick=()=>$('camera').click();for(const id of['gallery','camera'])$(id).onchange=e=>pick(e.target.files[0]);$('clearButton').onclick=clear;
$('recordForm').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!user){$('authDialog').showModal();return;}if(pending){say('يوجد سجل ينتظر الحفظ. أعد إرساله أولًا.');return;}if(!selected){say('اختر صورة أولًا.');return;}const name=$('name').value.trim();if(!name){say('اكتب الاسم.');return;}try{pending={id:crypto.randomUUID(),name,blob:selected.blob,original:selected.original};await storage('put',pending);renderPending();await send(pending);}catch(e){pending=null;renderPending();say('تعذر حفظ النسخة المؤقتة؛ لم تُرفع الصورة. '+e.message);}};
$('retryButton').onclick=()=>pending&&send(pending);$('refreshButton').onclick=async()=>{await status();await load();};$('authButton').onclick=async()=>{if(user){await db.auth.signOut();await session();}else $('authDialog').showModal();};$('closeAuth').onclick=()=>$('authDialog').close();$('authForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;const{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});btn.disabled=false;if(error){$('authMessage').textContent='تعذر الدخول: '+error.message;return;}$('password').value='';$('authDialog').close();await session();};
$('excelButton').onclick=()=>exportRun(excel);$('pdfButton').onclick=()=>exportRun(()=>makePDF(records));$('previewPDF').onclick=()=>exportRun(async()=>{if(!selected||!$('name').value.trim())throw Error('اكتب الاسم واختر صورة أولًا.');await makePDF([{name:$('name').value.trim(),image_url:previewURL,created_at:new Date().toISOString(),preview:true}]);});
window.addEventListener('online',async()=>{await status();if(pending&&cloudReady)await send(pending);});db.auth.onAuthStateChange(()=>{setTimeout(session,0);});status();session();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
